<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260213000000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Create favorites table for persistent anonymous favorites';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE favorites (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, client_id VARCHAR(36) NOT NULL, pokemon_name VARCHAR(100) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX uq_client_pokemon ON favorites (client_id, pokemon_name)');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('DROP TABLE favorites');
    }
}
